version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1
jobs:
  buildanddeploy:
    docker:
      - image: cimg/deploy:2022.07
        environment:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: $AWS_REGION
    working_directory: ~/workspace/circleci
    steps:
      - checkout
      - sonarcloud/scan
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # build and push Docker image and deploy to aws-eks
      - run: |            
          TAG = 0.3.${{CIRCLE_BUILD_NUM}}            
          docker build -t vijyant97/circleci:${TAG} .           
      - run: |    
          echo $DOCKER_PASS | docker login -u vijyant97 --password-stdin
      - run: |          
          docker run aquasec/trivy image vijyant97/circleci:${TAG} 
      - run: |    
          docker push vijyant97/circleci:${TAG}
      - run: |  
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip 
          sudo ./aws/install
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin 
      - run: |    
          sudo apt-get update -y          
          curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.6/2022-03-09/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
          aws eks --region eu-west-1 update-kubeconfig --name go-test-cluster
          kubectl apply -f service.yaml
          kubectl apply -f deployment.yaml        
workflows:
  version: 2
  build:
    jobs:
      - buildanddeploy:
          context: SonarCloud
          
      
          
