version: 2.1
orbs:
  nexus-platform-orb: sonatype/nexus-platform-orb@1.0.28 
jobs:
  buildanddeploy:
    docker:
      - image: openjdk
    working_directory: ~/workspace/circleci
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
           mkdir /etc/docker/
           cd /etc/docker/
           echo "{ "insecure-registries" : ["ec2-99-80-60-200.eu-west-1.compute.amazonaws.com:8085"]           }" >> daemon.json
           cat daemon.json
       - run: |
           sudo service docker restart
      - run: |    
          #sudo docker login -u admin nexus_public_dns_name:8085
          echo $DOCKER_PASS | docker login -u admin ${{ DOCKER_USER }}:8085 --password-stdin 
          docker build . -t ${{ DOCKER_USER }}:8085/circleci_test_golang           
      - run: |    
          sudo docker push ${ DOCKER_USER}:8085/circleci_test_golang
workflows:
  version: 2
  build:
    jobs:
      - buildanddeploy
